name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Defina a versão do Python para o projeto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que esse arquivo lista as dependências do projeto

      - name: Run tests
        run: |
          pytest  # Substitua pelo comando de teste adequado, ex: pytest para projetos Python
